{{- if .Values.clusterissuer.staging.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.staging.name }}
spec:
  acme:
    email: {{ required "A valid .Values.clusterissuer.staging.email entry required!" .Values.clusterissuer.staging.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ .Values.clusterissuer.staging.privateKeySecretRef }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
